## 00. PyTorch Fundamentals Exercises
1. **Documentation reading**
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

The documentation on torch.Tensor.
The documentation on torch.cuda.

In [1]:
import torch
import numpy as np

2. Create a random tensor with shape (7, 7).

In [5]:
tensor_A = torch.rand(size=(7, 7), dtype=torch.float16)
tensor_A

tensor([[0.1724, 0.3560, 0.1479, 0.2534, 0.6118, 0.5078, 0.9087],
        [0.0400, 0.2891, 0.2505, 0.1353, 0.0166, 0.8657, 0.0557],
        [0.3804, 0.5400, 0.4375, 0.7207, 0.9702, 0.7808, 0.2271],
        [0.7422, 0.5508, 0.8359, 0.4712, 0.4741, 0.5874, 0.5229],
        [0.8018, 0.8506, 0.1738, 0.1743, 0.1460, 0.7559, 0.4922],
        [0.4658, 0.0801, 0.8296, 0.0190, 0.7251, 0.6685, 0.7080],
        [0.7402, 0.5630, 0.6309, 0.4082, 0.0996, 0.3804, 0.3486]],
       dtype=torch.float16)

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [6]:
tensor_B = torch.rand(size=(1, 7), dtype=torch.float16)
tensor_B

tensor([[0.6826, 0.0713, 0.7280, 0.9775, 0.7817, 0.2090, 0.0034]],
       dtype=torch.float16)

In [7]:
product = torch.matmul(tensor_A, tensor_B.T)
product

tensor([[1.0859],
        [0.5566],
        [2.2441],
        [2.1094],
        [1.1787],
        [1.6553],
        [1.5625]], dtype=torch.float16)

4. Set the random seed to 0 and do 2 & 3 over again.

In [9]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(size=(7, 7), dtype=torch.float16)
tensor_D = torch.rand(size=(1, 7),dtype=torch.float16 )
output_seed = torch.matmul(tensor_C, tensor_D.T)
print(output_seed)

tensor([[1.8789],
        [2.0254],
        [1.6543],
        [1.1338],
        [1.3369],
        [2.3633],
        [1.5859]], dtype=torch.float16)


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

* If there is, set the GPU random seed to 1234.

In [3]:
import torch
torch.cuda.manual_seed(123)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
torch.manual_seed(1234)
tensor_X = torch.rand(size=(2, 3), dtype=torch.float16).to(device)
tensor_Z = torch.rand(size=(2, 3), dtype=torch.float16).to(device)
print(tensor_X, tensor_Z)

tensor([[0.3979, 0.3530, 0.6436],
        [0.5259, 0.5996, 0.6816]], device='cuda:0', dtype=torch.float16) tensor([[0.3242, 0.9966, 0.8198],
        [0.3364, 0.1362, 0.6138]], device='cuda:0', dtype=torch.float16)


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [9]:
out = torch.matmul(tensor_X, tensor_Z.T)
out

tensor([[1.0088, 0.5771],
        [1.3271, 0.6768]], device='cuda:0', dtype=torch.float16)

8. Find the maximum and minimum values of the output of 7.

In [10]:
out.max()

tensor(1.3271, device='cuda:0', dtype=torch.float16)

In [11]:
out.min()

tensor(0.5771, device='cuda:0', dtype=torch.float16)

9. Find the maximum and minimum index values of the output of 7.

In [12]:
out.argmin()

tensor(1, device='cuda:0')

In [13]:
out.argmax()

tensor(2, device='cuda:0')

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [17]:
tensor_F = torch.rand(size=(1, 1, 1, 10))
tensor_F = torch.squeeze(tensor_F, dim=3)
tensor_F.shape

torch.Size([1, 1, 1, 10])

In [20]:
torch.manual_seed(7)
tensor_F = torch.rand(size=(1, 1, 1, 10))
tensor_G = torch.squeeze(tensor_F)
tensor_F.shape, tensor_G.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))