In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## Introduction to Tensors
### Creating Tensors
PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

Get tensor back as a pthon `int`

In [4]:
scaler.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 7],
                       [4, 7]])
MATRIX

tensor([[7, 7],
        [4, 7]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 7])

In [11]:
MATRIX[1]

tensor([4, 7])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
## TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 7],
                        [2, 3, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 7],
         [2, 3, 5]]])

In [14]:
TENSOR.ndim

3

For visualizing

 https://i-blog.csdnimg.cn/blog_migrate/8d3ee59561eadbe6647b2fdc3f75c8f8.png

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 7],
        [2, 3, 5]])

## Random Tensors
### Why random tensors?
Random tensors are important because the way many neural networks learn is that they  start with tensors full of random numbers and then adjust those random numbers to better represent the data.
` Start with random numbers -> Look at the data -> Update random numbers -> Look at the data -> Update random numbers `


Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3515, 0.7742, 0.8658, 0.1604],
        [0.3892, 0.3421, 0.3477, 0.2511],
        [0.5566, 0.4439, 0.5262, 0.3726]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor2 = torch.rand(1, 3, 4)
random_tensor2

tensor([[[0.1061, 0.1833, 0.7444, 0.2250],
         [0.4967, 0.0037, 0.7646, 0.6484],
         [0.6297, 0.6883, 0.4268, 0.7044]]])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor

tensor([[[0.5056, 0.6071, 0.3857],
         [0.7945, 0.2361, 0.2503],
         [0.6624, 0.9947, 0.5278],
         ...,
         [0.9932, 0.2894, 0.5611],
         [0.1418, 0.4929, 0.8160],
         [0.0147, 0.7551, 0.8962]],

        [[0.3656, 0.3600, 0.8142],
         [0.7613, 0.3114, 0.8125],
         [0.5843, 0.0088, 0.7221],
         ...,
         [0.8384, 0.7030, 0.9919],
         [0.5671, 0.4635, 0.1610],
         [0.5944, 0.2211, 0.2244]],

        [[0.1894, 0.6979, 0.0955],
         [0.0362, 0.7310, 0.4496],
         [0.0753, 0.6294, 0.9993],
         ...,
         [0.5285, 0.2809, 0.3865],
         [0.2144, 0.8357, 0.9056],
         [0.7476, 0.6687, 0.1652]],

        ...,

        [[0.5297, 0.8662, 0.4893],
         [0.9332, 0.0981, 0.5113],
         [0.1171, 0.5960, 0.7824],
         ...,
         [0.5243, 0.2675, 0.5078],
         [0.1236, 0.9145, 0.5986],
         [0.1931, 0.3404, 0.4014]],

        [[0.5689, 0.8820, 0.4235],
         [0.0029, 0.8577, 0.7072],
         [0.

In [21]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

## Zeros and Ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(4, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

## Creating a range of tensors and tesnors-like.

In [26]:
# Use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
range_step = torch.arange(start=0, end=1000, step=77)
range_step

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [28]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
**Note:** Tensor datatype is one of the 3 big errors you will run into with issues  PyTorch & Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 6.0], dtype=None)
print(f"The datatype of tensor if None is passed as dtype is {float_32_tensor.dtype}")

The datatype of tensor if None is passed as dtype is torch.float32


In [30]:
float_16_tensor = torch.tensor([3.0, 6.0, 6.0], dtype=torch.float16)
print(f"The datatype of tensor if float16 is passed as dtype is {float_16_tensor.dtype}")

The datatype of tensor if float16 is passed as dtype is torch.float16


In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 6.0],
                               dtype=None, # what datatype is the tensor (e.g float32, float16, float64)
                               device=None, # None is cpu as default
                               requires_grad=False )# whether or not to track gradients with this tensors operations

In computer science, the precision of a numerical quantity is a measure of the detail in which the quantity is expressed. This is usually measured in bits, but sometimes in decimal digits. It is related to precision in mathematics, which describes the number of digits that are used to express a value

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 6.], dtype=torch.float16)

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 36.])

In [34]:
int_32_tensor = torch.tensor([2, 3, 6], dtype=torch.int32)

In [35]:
int_32_tensor * float_32_tensor

tensor([ 6., 18., 36.])

## Getting Information from Tensor (tensor attributes)
**Note:** Tensor datatype is one of the 3 big errors you will run into with issues  PyTorch & Deep Learning
1. Tensors not right datatype - to do get datatype can use `torch.dtype`
2. Tensors not right shape - to do get shape can use `torch.shape`
3. Tensors not on the right device - to get device can use `torch.device`

In [36]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3203, 0.7072, 0.6833, 0.8103],
        [0.6625, 0.4299, 0.5068, 0.9024],
        [0.7303, 0.2439, 0.8829, 0.8820]])

In [37]:
# Find out details about some tensor
print(some_tensor)
print(f"DataType of the Tensor: {some_tensor.dtype}")
print(f"Shape of the Tensor : {some_tensor.shape} ")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.3203, 0.7072, 0.6833, 0.8103],
        [0.6625, 0.4299, 0.5068, 0.9024],
        [0.7303, 0.2439, 0.8829, 0.8820]])
DataType of the Tensor: torch.float32
Shape of the Tensor : torch.Size([3, 4]) 
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (Element-wise)
* Divison
* Matrix Multiplication


In [38]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3], dtype=torch.float16)
tensor = tensor + 10


In [39]:
# Multiply tensor by 10
tensor * 10

tensor([110., 120., 130.], dtype=torch.float16)

In [40]:
# Subtraction by 10
tensor - 10

tensor([1., 2., 3.], dtype=torch.float16)

### Try out PyTorch in-built functions

In [41]:
# Multiplication:-
torch.mul(tensor, 10)

tensor([110., 120., 130.], dtype=torch.float16)

In [42]:
torch.add(tensor, 10)

tensor([21., 22., 23.], dtype=torch.float16)

# Matrix  multiplication
Two main ways of  performing matrix multiplication in nueral networs and deep learning:-
1. Element-wise multiplication
2. Matrix Multiplication
More info on  multiplying matrices : https://www.mathsfun.com/algebra/matrix-multiplying.html

In [43]:
# Element wise multiplication
print(f"{tensor}  *  {tensor}")
print(f"Equals : {tensor*tensor}")

tensor([11., 12., 13.], dtype=torch.float16)  *  tensor([11., 12., 13.], dtype=torch.float16)
Equals : tensor([121., 144., 169.], dtype=torch.float16)


In [44]:
torch.matmul(tensor, tensor)

tensor(434., dtype=torch.float16)

In [45]:
tensor

tensor([11., 12., 13.], dtype=torch.float16)

In [46]:
# Matrix multiplication by hand
11*11 + 12*12 + 13*13

434

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(434., dtype=torch.float16)
CPU times: user 2.72 ms, sys: 0 ns, total: 2.72 ms
Wall time: 2.44 ms


In [48]:
%%time
value = 0
torch.matmul(tensor, tensor)
print(value)

0
CPU times: user 386 µs, sys: 59 µs, total: 445 µs
Wall time: 379 µs


### One of the  most common errors in deep learning : shape errors
1. The **inner dimmensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3)@ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix  has the shape of **outer dimmensions**:
* `(2,3) @ (3,2)` ->> `(2, 2)`
* `(3,2) @ (2,3)` ->> `(3, 3)`

In [49]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.9156, 0.8749, 0.8468],
        [0.5583, 0.5392, 0.5126],
        [0.4047, 0.3693, 0.3856]])

In [50]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,  2],
                         [3,  4],
                         [5,  6]])

tensor_B = torch.tensor([[7,  10],
                         [8,  11],
                         [9,  12]])

# torch.mm(tensor_A, tensor_B)

In [51]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manupulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or a dimension of a given tensor

In [52]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [53]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [54]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [55]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape } (same shape as above ) , tensor_B.T = {tensor_B.T}")
print(f"After multiplying {tensor_A}*{tensor_B.T.shape} < - inner dimmension must match")
print(f"Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(f"\nThe output is {output} and the shape is {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above ) , tensor_B.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
After multiplying tensor([[1, 2],
        [3, 4],
        [5, 6]])*torch.Size([2, 3]) < - inner dimmension must match
Output:


The output is tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) and the shape is torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregeation)

In [56]:
# Create a Tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [58]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [59]:
# Find the mean :- The torch.mean() function requires of float32
torch.mean(x.type(torch.float32))

tensor(45.)

In [60]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [61]:
# Find the posotion in the tensor that has minimum value with argmin() -> rtrn the index position of target tensor where the min value occur
x.argmin()

tensor(0)

In [62]:
x[0]

tensor(0)

In [63]:
# Find the posotion in the tensor that has maximum value with argmax() -> rtrn the index position of target tensor where the max value occur
x.argmax()

tensor(9)

In [64]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors:
* Reshaping  - reshapes the input tensor to a defined shape
* View - return a view of input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on the top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target column
* Permute - Return a view of a input with dimension permuted (swaped) in a certain wat

In [71]:
# Let's create a Tensor
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [72]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [74]:
# Change the review
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [77]:
#  stack tensors on the top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [78]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [87]:
# torch.squeeze - removes all 1 dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor : {x_squeezed}")
print(f"\nShape of new Tensor: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape: torch.Size([1, 9])

New Tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

Shape of new Tensor: torch.Size([9])


In [88]:
# torch.unsqueeze() - adds a single dimension to a target tensor at specific dim (dimensions)
print(f"Previous Target : {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\n New Target : {x_unsqueezed}")
print(f"\n New Shape : {x_unsqueezed.shape}")

Previous Target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

 New Target : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

 New Shape : torch.Size([1, 9])


In [89]:
# torch.unsqueeze() - adds a single dimension to a target tensor at specific dim (dimensions)
print(f"Previous Target : {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\n New Target : {x_unsqueezed}")
print(f"\n New Shape : {x_unsqueezed.shape}")

Previous Target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

 New Target : tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

 New Shape : torch.Size([9, 1])


In [92]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channel]

# Permute to original  tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1 , 1->2, 2->0

print(f"Original Shape : {x_original.shape}")
print(f"\nPermuted Shape:{x_permuted.shape}") # [color_channel, height, width]
# Memory would be same

Original Shape : torch.Size([224, 224, 3])

Permuted Shape:torch.Size([3, 224, 224])


## Indexing
### Selecting data from Tensors
#### Indexing with PyTorch is smiliar to indexing of Numpy

In [93]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [94]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [96]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [97]:
# Let's index on the  most inner bracket
x[0][0][0]

tensor(1)

In [98]:
x[0][0][1]

tensor(2)

In [99]:
x[0][2][2]

tensor(9)

In [100]:
# we can use ":" to select all of a target dimensions
x[:, 0]

tensor([[1, 2, 3]])

In [101]:
x[:, 0, 1]

tensor([2])

In [102]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [103]:
# Get index  0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy
Numpy is popular scientific Python numerical computing library
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want to PyTorch Tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [106]:
## Numpy array to tensor
import numpy as np
import torch
print(f"The version of numpy : {np.__version__}")
print(f"The version of PyTorch : {torch.__version__}")

The version of numpy : 2.0.2
The version of PyTorch : 2.9.0+cu126


In [110]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [111]:
# Change the value of array, what will this do to `tensor`?
array +=1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [112]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)
In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...`
To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**

Especially what the random seeds does is "flavour" the randomness.

In [116]:
torch.rand(3, 3)

tensor([[0.2764, 0.0165, 0.5296],
        [0.1353, 0.0898, 0.5808],
        [0.1361, 0.1322, 0.2227]])

In [124]:
# Create two random tensor
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6134, 0.9973, 0.0900, 0.9691],
        [0.4017, 0.8456, 0.9165, 0.8637],
        [0.6079, 0.2722, 0.0181, 0.3334]])
tensor([[0.2172, 0.3623, 0.2977, 0.9732],
        [0.2031, 0.2210, 0.8641, 0.8030],
        [0.7213, 0.4322, 0.8510, 0.7096]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [128]:
# Let's make some random tensors but reproducible tensors
import torch


# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Extra resources for Reproduciblity
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipeda.org/wiki/Random_seed

### Running tensors and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky

### Getting a GPU
1. Easiest - Use google Colab for free GPU
2. Use your own GPU - takes a little bit of setupand requires the investment
3. Use cloud computing - GCP, AWS, Azure these services allows you to rent computers on the cloud and acess them.

In [1]:
!nvidia-smi

Mon Dec  8 03:10:42 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access with PyTorch

In [2]:
# Check
import torch
torch.cuda.is_available()


True

In [7]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

Learn more from this https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

### Putting Tensors (and models) on GPUs
The reason we want tensors/models on the GPU for faster computation

In [6]:
## Create a tensor (default on the CPUs)
tensor = torch.tensor([1, 2, 3])
## Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
##  Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

### Moving tensor back to the cpu

In [10]:
# if tensor in on gpu can't transform it to NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy
tensor_back_on_cpu

<function Tensor.numpy>

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')