In [36]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [37]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [38]:
df.shape

(569, 33)

In [39]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [40]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train-Test Split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

### Scaling

In [42]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [43]:
X_train

array([[ 0.85255024, -0.68782575,  0.98798593, ...,  2.14791313,
         2.01602905,  1.20171556],
       [-0.14467499, -0.70198964, -0.20415167, ..., -0.45009981,
        -0.90802647, -0.22009909],
       [-0.54071587,  0.7380064 , -0.57806631, ..., -0.79585641,
         0.37379787, -0.12143125],
       ...,
       [-0.19596086, -0.13307317, -0.19462782, ...,  0.42297017,
         1.08441136,  0.13466168],
       [ 1.10043194,  0.29420434,  1.08736523, ...,  0.51820299,
         0.63050274, -0.44182457],
       [ 0.73858164,  0.53735122,  0.74367846, ...,  1.01587131,
         3.37095478,  0.11692364]])

In [44]:
y_train

25     M
51     B
490    B
54     M
362    B
      ..
301    B
44     M
526    B
492    M
35     M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [45]:
encoder = LabelEncoder()

In [46]:
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [47]:
y_train

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,

### NumPy arrays to PyTorch tensors

In [48]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [49]:
X_train_tensor.shape

torch.Size([455, 30])

In [50]:
y_train_tensor.shape

torch.Size([455])

### Defining the Model

In [51]:
class MySimpleNN():

  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad = True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss =  -(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss




### Important parameters

In [52]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [53]:
# create_model
model = MySimpleNN(X_train_tensor)
# define loop
for epoch in range(epochs):
  # Forward Pass
  y_pred = model.forward(X_train_tensor)
  #print(y_pred)

  # loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)

  # backprop
  loss.backward()

  # paramters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epochs
  print(f"Epoch: {epoch+1}, Loss : {loss.item()}")

Epoch: 1, Loss : 3.2801166348780186
Epoch: 2, Loss : 3.128103129631412
Epoch: 3, Loss : 2.975430808073563
Epoch: 4, Loss : 2.8178121055818077
Epoch: 5, Loss : 2.655806204659787
Epoch: 6, Loss : 2.4918027273270713
Epoch: 7, Loss : 2.3255224661737532
Epoch: 8, Loss : 2.1615764737954395
Epoch: 9, Loss : 2.000735506494414
Epoch: 10, Loss : 1.8421430489308295
Epoch: 11, Loss : 1.6872989725715206
Epoch: 12, Loss : 1.5391442412285596
Epoch: 13, Loss : 1.3962848526106364
Epoch: 14, Loss : 1.268214369812622
Epoch: 15, Loss : 1.1563795438722149
Epoch: 16, Loss : 1.061757887179089
Epoch: 17, Loss : 0.984549579668594
Epoch: 18, Loss : 0.9239291070594757
Epoch: 19, Loss : 0.8780259636688844
Epoch: 20, Loss : 0.8441999183292546
Epoch: 21, Loss : 0.8195328107599731
Epoch: 22, Loss : 0.8013520731227848
Epoch: 23, Loss : 0.7875617675444627
Epoch: 24, Loss : 0.7766947673186219
Epoch: 25, Loss : 0.7677936518154467


### Evaluation

In [56]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
print(y_pred)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
      

### Accuarcy

In [58]:
accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuarcy : {accuracy.item()}")

Accuarcy : 0.55755615234375
