In [6]:
import torch
import torch.nn as nn

In [13]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out


In [14]:
features = torch.rand(10,5)
features

tensor([[0.7473, 0.0957, 0.6888, 0.4384, 0.6091],
        [0.0183, 0.7606, 0.6946, 0.6374, 0.9918],
        [0.4499, 0.6083, 0.2306, 0.1252, 0.7234],
        [0.2168, 0.4276, 0.2674, 0.4505, 0.0684],
        [0.7907, 0.4898, 0.1920, 0.8424, 0.5366],
        [0.4174, 0.4213, 0.8873, 0.4415, 0.2278],
        [0.1846, 0.0176, 0.7847, 0.8126, 0.7630],
        [0.7760, 0.0237, 0.0794, 0.0816, 0.5304],
        [0.5187, 0.5625, 0.8536, 0.6715, 0.1692],
        [0.0755, 0.3005, 0.7197, 0.9548, 0.0367]])

In [15]:
model = Model(features.shape[1])

model(features)

tensor([[0.4098],
        [0.4339],
        [0.4306],
        [0.3897],
        [0.4078],
        [0.3608],
        [0.4433],
        [0.4428],
        [0.3461],
        [0.3722]], grad_fn=<SigmoidBackward0>)

In [16]:
model.linear.weight

Parameter containing:
tensor([[-0.1616, -0.2305, -0.2420, -0.0110,  0.3605]], requires_grad=True)

In [17]:
model.linear.bias

Parameter containing:
tensor([-0.2700], requires_grad=True)

In [18]:
!pip install torchinfo

In [19]:
from torchinfo import summary

In [20]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00