In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available using CPU .")

GPU is available
Using GPU: Tesla T4


## Creating Tensor

In [4]:
#using empty
torch.empty(2,3)
a=torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using random :- diff output every time
torch.rand(2,3)

tensor([[0.5434, 0.0710, 0.3044],
        [0.0957, 0.9771, 0.0150]])

In [10]:
# manual seed :- same output
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[2,4,5]])

tensor([[1, 2, 3],
        [2, 4, 5]])

In [12]:
#arrange
print("using arrange ->", torch.arange(0,10,2))
# using linspace
print("Using linspace -> ", torch.linspace(0,10,10))
# using eye
print("using eye -> ", torch.eye(5))
#using full
print("using full -> ", torch.full((3,3),5))

using arrange -> tensor([0, 2, 4, 6, 8])
Using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 4049914974328415077]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [27]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Datatypes

In [18]:
x.dtype

torch.int64

In [20]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
a=x.to(torch.float32)

In [26]:
a.dtype

torch.float32

In [33]:
# Addition
x+2
# Subtraction
x-2
# multiplication
x*2
# divison
x/2
# int divison
(x*100)//2
# mod
((x*100)//2)%2
# power
x**2


tensor([[ 1,  4,  9],
        [16, 25, 36]])

## Element wise Operation

In [34]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [38]:
#add
a+b
# subtract
a-b
# multiply
a*b
# divison
a/b
# power
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [39]:
c = torch.tensor([1,-2,3,-4])

In [40]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [41]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [42]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [43]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [44]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [45]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [46]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction Operations

In [55]:
e = torch.randint(size=(2,3),low=0, high=3, dtype=torch.float32)
f = torch.randint(size=(2,3),low=0, high=3, dtype = torch.float32)
e

tensor([[0., 0., 0.],
        [0., 1., 0.]])

In [56]:
#sum
torch.sum(e)

tensor(1.)

In [57]:
# sum along columns
torch.sum(e,dim=0)


tensor([0., 1., 0.])

In [58]:
# sum along rows
torch.sum(e,dim=1)

tensor([0., 1.])

In [59]:
# mean
torch.mean(e)

tensor(0.1667)

In [60]:
# columns
torch.mean(e,dim=0)

tensor([0.0000, 0.5000, 0.0000])

In [61]:
# rows
torch.mean(e,dim=1)

tensor([0.0000, 0.3333])

In [63]:
#max
torch.max(e)
#min
torch.min(e)

tensor(0.)

In [64]:
# product
torch.std(e)

tensor(0.4082)

In [65]:
# standard deviation
torch.var(e)

tensor(0.1667)

In [67]:
# position of max item
torch.argmax(e)

tensor(4)

In [69]:
# position of mix item
torch.argmin(e)

tensor(0)

In [77]:
k = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
l = torch.randint(size=(3,2),low=0, high=10, dtype = torch.float32)

In [74]:
print(k)

tensor([[8., 3., 3.],
        [5., 0., 6.]])


In [75]:
print(l)

tensor([[4., 0., 8.],
        [4., 7., 2.]])


In [78]:
# matrix multiplication
torch.matmul(k,l)

tensor([[ 82.,  21.],
        [101.,  13.]])

In [79]:
vector_1 = torch.tensor([1,2])
vector_2 = torch.tensor([4,5])

In [80]:
torch.dot(vector_1,vector_2)

tensor(14)

In [81]:
# transpose
torch.transpose(f,0,1)

tensor([[5., 4.],
        [5., 3.],
        [0., 8.]])

In [83]:
h=torch.randint(size=(3,3),low=0,high=10, dtype=torch.float32)

In [85]:
torch.det(h)

tensor(-71.)

In [86]:
# inverse
torch.inverse(h)

tensor([[-0.0423,  0.2676, -0.0141],
        [ 0.3662,  0.0141, -0.2113],
        [-0.1972, -0.0845,  0.2676]])

## Comparison Operations

In [89]:
x = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
y = torch.randint(size=(2,3),low=0, high=10, dtype = torch.float32)

In [93]:
# greater than
x > y
# less than
x < y
# equals to
x == y
# not equals to
x != y

tensor([[True, True, True],
        [True, True, True]])

## Special Functions

In [94]:
#log
torch.log(x)

tensor([[0.6931, 0.0000, 0.6931],
        [1.9459, 2.1972, 0.6931]])

In [95]:
# exp
torch.exp(x)

tensor([[7.3891e+00, 2.7183e+00, 7.3891e+00],
        [1.0966e+03, 8.1031e+03, 7.3891e+00]])

In [96]:
# square root
torch.sqrt(x)

tensor([[1.4142, 1.0000, 1.4142],
        [2.6458, 3.0000, 1.4142]])

In [97]:
# sigmoid
torch.sigmoid(x)

tensor([[0.8808, 0.7311, 0.8808],
        [0.9991, 0.9999, 0.8808]])

In [100]:
# softmax
torch.softmax(x,dim=0)

tensor([[6.6929e-03, 3.3535e-04, 5.0000e-01],
        [9.9331e-01, 9.9966e-01, 5.0000e-01]])

In [101]:
torch.relu(x)

tensor([[2., 1., 2.],
        [7., 9., 2.]])

## Inplace Operations

In [102]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [103]:
print(m)
print(n)

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])
tensor([[0.8993, 0.2732, 0.3397],
        [0.1879, 0.5534, 0.2682]])


In [104]:
m+n

tensor([[1.5681, 0.5384, 0.5734],
        [0.6936, 1.1222, 0.3315]])

In [105]:
m.add_(n)

tensor([[1.5681, 0.5384, 0.5734],
        [0.6936, 1.1222, 0.3315]])

In [106]:
m

tensor([[1.5681, 0.5384, 0.5734],
        [0.6936, 1.1222, 0.3315]])

In [107]:
n

tensor([[0.8993, 0.2732, 0.3397],
        [0.1879, 0.5534, 0.2682]])

In [108]:
m.relu_()

tensor([[1.5681, 0.5384, 0.5734],
        [0.6936, 1.1222, 0.3315]])

In [109]:
m

tensor([[1.5681, 0.5384, 0.5734],
        [0.6936, 1.1222, 0.3315]])

## Copying a Tensor


In [110]:
a = torch.rand(3,4)

In [111]:
# deep copy
b=a

In [112]:
b = a.clone()

## Tensors on GPU

In [113]:
torch.cuda.is_available()

True

In [114]:
device = torch.device('cuda')

In [115]:
# creating new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [116]:
# moving an exsisting tensor on gpu from cpu
a = torch.rand(2,3)

In [118]:
b=a.to(device)

In [120]:
import time
size = 10000
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time()-start_time
print(f"Time on CPU : {cpu_time:.4f} seconds")

matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time = start_time - time.time()
print(f"Time on GPU : {gpu_time:.4f} seconds")

Time on CPU : 16.1462 seconds
Time on GPU : -0.7259 seconds


## Reshaping Tensors

In [122]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [124]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [125]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
b = torch.rand(2,3,4)

In [127]:
b

tensor([[[0.1433, 0.7931, 0.7799, 0.3788],
         [0.2750, 0.3103, 0.1942, 0.4751],
         [0.9200, 0.0472, 0.5397, 0.7160]],

        [[0.2801, 0.6461, 0.9829, 0.0332],
         [0.6062, 0.9161, 0.5627, 0.7324],
         [0.0059, 0.0328, 0.6305, 0.4399]]])

In [128]:
b.permute(2,0,1)

tensor([[[0.1433, 0.2750, 0.9200],
         [0.2801, 0.6062, 0.0059]],

        [[0.7931, 0.3103, 0.0472],
         [0.6461, 0.9161, 0.0328]],

        [[0.7799, 0.1942, 0.5397],
         [0.9829, 0.5627, 0.6305]],

        [[0.3788, 0.4751, 0.7160],
         [0.0332, 0.7324, 0.4399]]])

In [129]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [132]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0)

tensor([0.5778, 0.2294, 0.3925, 0.9999, 0.9077, 0.4143, 0.2458, 0.9170, 0.2747,
        0.8820, 0.2015, 0.7016, 0.7013, 0.4521, 0.9451, 0.7654, 0.2137, 0.4166,
        0.2945, 0.4468])

## NumPy and PyTorch

In [133]:
import numpy as np
a = torch.tensor([1,2,3])

In [134]:
b = a.numpy()

In [135]:
b

array([1, 2, 3])

In [136]:
c = np.array([1,2,3])
torch.from_numpy(c)

tensor([1, 2, 3])